[package]
name = "rust-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.88"
bigdecimal = "0.4.6"
clap = { version = "4.5.17", features = ["derive"] }
rand = "0.9.0-alpha.2"
